apiVersion: apps/v1

kind: Deployment

metadata:
  name: tictactoe-dev

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe-dev

  template:
      metadata:
        labels:
          app: tictactoe-dev
      spec:
        containers:
          - name: tictactoe
            image: IMAGE_PLACEHOLDER
            imagePullPolicy: Always
            ports:
              - containerPort: 80


