apiVersion: apps/v1
kind: Deployment

metadata:
  name: tictactoe-prod

spec:
  replicas: 2

  selector:
    matchLabels:
      app: tictactoe-prod

  template:
    metadata:
      labels:
        app: tictactoe-prod

    spec:
      containers:
        - name: tictactoe-prod
          image: thejohnbaba/tictactoe-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80